create table if not exists public.upgrade_suggestions (
    id bigint generated by default as identity primary key,
    email text not null,
    suggestion text not null,
    created_at timestamptz not null default now(),
    constraint suggestion_length check (char_length(suggestion) between 1 and 1000)
);

alter table public.upgrade_suggestions enable row level security;

grant insert on public.upgrade_suggestions to anon;

drop policy if exists "Anyone can submit upgrade suggestions" on public.upgrade_suggestions;
create policy "Anyone can submit upgrade suggestions"
on public.upgrade_suggestions
for insert
to anon
with check (char_length(email) <= 320 and char_length(suggestion) between 1 and 1000);
